!obj:galatea.s3c.extract_features.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "${GALATEA_PATH}/s3c/config/stl/JS2.pkl",         "pooling_region_counts": [2,3],
        "save_paths" : [ "${FEATURE_EXTRACTOR_YAML_PATH}_2.npy",  "${FEATURE_EXTRACTOR_YAML_PATH}_3.npy" ], 
        "feature_type" : "exp_h", 
        "dataset_name" : "stl10",
        "which_set" : "train"
}       
