!obj:pylearn2.train.Train {
    dataset: &train !obj:galatea.datasets.zca_dataset.ZCA_Dataset {
        preprocessed_dataset: !pkl: "${PYLEARN2_GCN_WHITENED}/train.pkl",
        preprocessor: !pkl: "${PYLEARN2_GCN_WHITENED}/preprocessor.pkl",
        start: 0,
        stop: 40000,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 128,
        layers: [
                 !obj:galatea.mlp.MaxPoolRectifiedLinear {
                    layer_name: 'h0',
                    irange: .005,
                    detector_layer_dim: 4000,
                    pool_size: 5,
                    max_col_norm: 1.9
                 },
                 !obj:galatea.mlp.MaxPoolRectifiedLinear {
                    layer_name: 'h1',
                    irange: .005,
                    detector_layer_dim: 4000,
                    pool_size: 5,
                    max_col_norm: 1.9
                 },
                 !obj:galatea.mlp.MaxPoolRectifiedLinear {
                    layer_name: 'h2',
                    irange: .005,
                    detector_layer_dim: 4000,
                    pool_size: 5,
                    max_col_norm: 1.9
                 },
                 !obj:galatea.mlp.MaxPoolRectifiedLinear {
                    layer_name: 'h3',
                    irange: .005,
                    detector_layer_dim: 4000,
                    pool_size: 5,
                    max_col_norm: 1.9
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     # 2AKB: tried doubling all norm constraints, hurt slightly
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 10,
                     irange: .005
                 }
                ],
        nvis: 3072,
        # 2AKE: tried setting first layer include prob to 1, hurt
        # performance significantly
        dropout_include_probs: [ .5, .5, .5, .5, 1 ],
        dropout_input_include_prob: .8,
        dropout_input_scale: 1.,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .1,
        # 2AK4: tried decreasing init_momentum to 0., hurt moderately
        # 2Ak5: tried decreasing init_momentum to 0.25
        #           killed after 24h, about 0.5 behind 2AK.
        init_momentum: .5,
        monitoring_dataset:
            {
                #'train' : *train,
                'valid' : !obj:galatea.datasets.zca_dataset.ZCA_Dataset {
                    preprocessed_dataset: !pkl: "${PYLEARN2_GCN_WHITENED}/train.pkl",
                    preprocessor: !pkl: "${PYLEARN2_GCN_WHITENED}/preprocessor.pkl",
                    start: 40000,
                    stop: 50000,
                          },
                #'test'  : !obj:pylearn2.datasets.cifar10.CIFAR10 {
                #              which_set: 'test',
                #              gcn: 55.,
                #              one_hot: 1,
                #          }
            },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            # 2AK8: Tried reducing final momentum to 0.6, hurt slightly
            final_momentum: .6
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 250,
            decay_factor: .01
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
