!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'unlabeled',
        scale: True,
    },
    model: !obj:galatea.adversarial.AdversaryPair {
        generator: !obj:galatea.adversarial.Generator {
            mlp: !obj:pylearn2.models.mlp.MLP {
            layers: [
                     !obj:pylearn2.models.mlp.RectifiedLinear {
                         layer_name: 'gh0',
                         dim: 8000,
                         sparse_init: 15,
                         max_col_norm: 1.9635
                     },
                     !obj:pylearn2.models.mlp.Sigmoid {
                         layer_name: 'h1',
                         dim: 8000,
                         sparse_init: 15,
                         init_bias: -2,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.mlp.Linear {
                         max_row_norm: 3.,
                         layer_name: 'y',
                         init_bias: .5,
                         sparse_init: 15,
                         sparse_stdev: .05,
                         dim: 1152
                     }
                    ],
            input_space: !obj:pylearn2.space.Conv2DSpace {
                shape: [48, 48],
                num_channels: 1,
                axes: ['b', 0, 1, 'c']
            }
        }},
        discriminator: 
            !obj:pylearn2.models.mlp.MLP {
            layers: [
                     !obj:pylearn2.models.maxout.Maxout {
                         layer_name: 'dh0',
                         num_units: 1200,
                         num_pieces: 5,
                         irange: .005,
                         max_col_norm: 1.9635,
                     },
                     !obj:pylearn2.models.maxout.Maxout {
                         layer_name: 'h1',
                         num_units: 1200,
                         num_pieces: 5,
                         irange: .005,
                         max_col_norm: 1.9365
                     },
                     !obj:pylearn2.models.mlp.Sigmoid {
                         layer_name: 'y',
                         dim: 1,
                         irange: .005,
                         max_col_norm: 1.9365
                     }
                    ],
            input_space: !obj:pylearn2.space.Conv2DSpace {
                shape: [48, 48],
                num_channels: 1,
                axes: ['b', 0, 1, 'c']
            }
        },
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: .025,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        monitoring_dataset:
            {
                #'train' : *train,
                'valid' : !obj:pylearn2.datasets.tfd.TFD {
                    which_set: 'valid',
                    scale: True,
                },
            },
        cost: !obj:galatea.adversarial.InpaintingAdversaryCost {
            no_drop_in_d_for_g: 1,
            scale_grads: 0,
            #target_scale: .1,
            discriminator_default_input_include_prob: .5,
            discriminator_input_include_probs: {
                'dh0': .8
            },
            discriminator_default_input_scale: 2.,
            discriminator_input_scales: {
                'dh0': 1.25   
            }
            },
        #!obj:pylearn2.costs.mlp.dropout.Dropout {
        #    input_include_probs: { 'h0' : .8 },
        #    input_scales: { 'h0': 1. }
        #},
        #termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
        #    channel_name: "valid_y_misclass",
        #    prop_decrease: 0.,
        #    N: 100
        #},
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.000004,
            min_lr: .000001
        }
    },
    extensions: [
        #!obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
        #     channel_name: 'valid_y_misclass',
        #     save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        #},
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 5
}
