!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'unlabeled',
        scale: True,
    },
    model: !obj:pylearn2.monitor.push_monitor {
        model: !pkl: "tfd_ian_5f.pkl",
        transfer_experience: 1,
        name: "old_monitor"
    },
    algorithm: !obj:galatea.adversarial.sgd.SGD {
        discriminator_steps: 5,
        batch_size: 100,
        learning_rate: .05,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        monitoring_dataset:
            {
                'subtrain' : !obj:pylearn2.datasets.tfd.TFD {
                            which_set: 'unlabeled',
                            scale: True,
                            example_range: [0, 10000]
                        },
                'valid' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'valid',
                              scale: True,
                          },
            },
        cost: !obj:galatea.adversarial.AdversaryCost2 {
            no_drop_in_d_for_g: 1,
            scale_grads: 0,
            #target_scale: 1.,
            discriminator_default_input_include_prob: .5,
            discriminator_input_include_probs: {
                'h0': .8
            },
            discriminator_default_input_scale: 2.,
            discriminator_input_scales: {
                'h0': 1.25
            }
            },
        #!obj:pylearn2.costs.mlp.dropout.Dropout {
        #    input_include_probs: { 'h0' : .8 },
        #    input_scales: { 'h0': 1. }
        #},
        #termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
        #    channel_name: "valid_y_misclass",
        #    prop_decrease: 0.,
        #    N: 100
        #},
        update_callbacks: [ !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.000004,
            min_lr: .000001
        },
         !obj:galatea.adversarial.Cycler {
            k: 5
        } ]
    },
    extensions: [
        #!obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
        #     channel_name: 'valid_y_misclass',
        #     save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        #},
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
