!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'unlabeled',
        scale: True,
    },
    model: !obj:galatea.adversarial.AdversaryPair {
        generator: !obj:galatea.adversarial.Generator {
            monitor_ll: 1,
            ll_sigma: .1,
            mlp: !obj:pylearn2.models.mlp.MLP {
            layers: [
                     !obj:pylearn2.models.mlp.RectifiedLinear {
                         layer_name: 'h0',
                         dim: 1200,
                         sparse_init: 15,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.mlp.RectifiedLinear {
                         layer_name: 'h1',
                         dim: 1200,
                         sparse_init: 15,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.mlp.Sigmoid {
                         layer_name: 'h2',
                         dim: 1200,
                         sparse_init: 15,
                         init_bias: -2,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.mlp.Linear {
                         max_row_norm: 3.,
                         init_bias: .5, # !obj:pylearn2.models.dbm.init_sigmoid_bias_from_marginals { dataset: *train},
                         layer_name: 'y',
                         irange: .005,
                         dim: 2304
                     }
                    ],
            nvis: 100,
        }},
        discriminator:
            !obj:pylearn2.models.mlp.MLP {
            layers: [
                    !obj:galatea.adversarial.SubtractHalf {
                        layer_name: 'subtract_half'
                    },
                     !obj:pylearn2.models.maxout.Maxout {
                         #W_lr_scale: .1,
                         #b_lr_scale: .1,
                         layer_name: 'h0',
                         num_units: 240,
                         num_pieces: 2,
                         irange: .005,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.maxout.Maxout {
                         #W_lr_scale: .1,
                         #b_lr_scale: .1,
                         layer_name: 'h1',
                         num_units: 240,
                         num_pieces: 2,
                         irange: .005,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.maxout.Maxout {
                         #W_lr_scale: .1,
                         #b_lr_scale: .1,
                         layer_name: 'h2',
                         num_units: 240,
                         num_pieces: 2,
                         irange: .005,
                         max_col_norm: 1.9365,
                     },
                     !obj:pylearn2.models.mlp.Sigmoid {
                         #W_lr_scale: .1,
                         #b_lr_scale: .1,
                         max_col_norm: 1.9365,
                         layer_name: 'y',
                         dim: 1,
                         irange: .005
                     }
                    ],
            nvis: 2304,
        },
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: .05,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        monitoring_dataset:
            {
                'subtrain' : !obj:pylearn2.datasets.tfd.TFD {
                            which_set: 'unlabeled',
                            scale: True,
                            example_range: [0, 10000]
                        },
                'valid' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'valid',
                              scale: True,
                          },
            },
        cost: !obj:galatea.adversarial.AdversaryCost2 {
            blend_obj: 1,
            #no_drop_in_d_for_g: 1,
            scale_grads: 0,
            #target_scale: 1.,
            discriminator_default_input_include_prob: .5,
            discriminator_input_include_probs: {
                'h0': .8
            },
            discriminator_default_input_scale: 2.,
            discriminator_input_scales: {
                'h0': 1.25
            }
            },
        #!obj:pylearn2.costs.mlp.dropout.Dropout {
        #    input_include_probs: { 'h0' : .8 },
        #    input_scales: { 'h0': 1. }
        #},
        #termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
        #    channel_name: "valid_y_misclass",
        #    prop_decrease: 0.,
        #    N: 100
        #},
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.000004,
            min_lr: .000001
        }
    },
    extensions: [
        #!obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
        #     channel_name: 'valid_y_misclass',
        #     save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        #},
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 5
}
