!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: &src "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
    "model": !obj:galatea.pddbm.pddbm.PDDBM {
        "dbm": !obj:pylearn2.models.dbm.DBM {
                "rbms" : [ !obj:pylearn2.models.rbm.RBM {
                                                  "nvis" : 625,
                                                  "nhid" : 1000
                                                }
                         ]
        },
        "s3c": !obj:galatea.s3c.s3c.S3C {
               "nvis" : 108,
               "nhid" : 1600,
               "init_bias_hid" : -4.,
               "max_bias_hid" : 0.,
               "min_bias_hid" : -7.,
               "irange"  : .02,
               "constrain_W_norm" : 1,
               "init_B"  : 3.,
               "min_B"   : .1,
               "max_B"   : 1e6,
               "tied_B" :  1,
               "init_alpha" : 1.,
               "min_alpha" : 1e-3,
               "max_alpha" : 1e6,
               "init_mu" : 0.,
               "random_patches_src" : *src,
               #"min_mu"  : 1.,
               #"max_mu"  : 1.,
               #"recycle_q" : 1000,
               "print_interval" : 10000,
               "monitor_functional" : 1,
               "monitor_params" : [ 'B', 'p', 'alpha', 'mu', 'W' ],
               #"monitor_stats" : [ 'mean_h', 'mean_hs', 'mean_sq_s', 'mean_sq_hs' ],
               "e_step" : !obj:galatea.s3c.s3c.E_Step {
                        #no damping coeffs since this is not where the schedule is specified anymore
                        "clip_reflections" : 1,
               },
               "m_step"     : !obj:galatea.s3c.s3c.Grad_M_Step {
                        "learning_rate" : 1e-2,
                        "B_learning_rate_scale" : 0.01,
                        "W_learning_rate_scale" : 10.,
                        "p_penalty" : 1.,
                        "B_penalty" : 1.,
                        "alpha_penalty" : 1.
               },
        },
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 100,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : !pkl: "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
                        "num_examples" : 100
                }
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

