#like D4 but added penalty on h
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: &src "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
    "model": !obj:galatea.pddbm.pddbm.PDDBM {
        "learning_rate" : .01,
        "dbm": !obj:pylearn2.models.dbm.DBM {
                "negative_chains" : 100,
                "monitor_params" : 1,
                "rbms" : [ !pkl: "/u/goodfeli/galatea/pddbm/config/stl/6x6/layer_2_B.pkl"
                         ]
        },
        "s3c": !pkl: "/u/goodfeli/galatea/pddbm/config/stl/6x6/layer_1_A.pkl",
       "inference_procedure" : !obj:galatea.pddbm.pddbm.InferenceProcedure {
                "schedule" : [ ['s',1.],   ['h',1.],   ['g',0],   ['h', 0.4], ['s',0.4],
                             ['h',0.4], ['g',0],   ['h',0.4], ['s',0.4],  ['h',0.4],
                             ['g',0],   ['h',0.4], ['s',0.4], ['h', 0.4], ['g',0],
                             ['h',0.4], ['g',0],   ['h',0.4], ['s', 0.4], ['h',0.4] ],
                "monitor_kl" : 0,
                "clip_reflections" : 1,
                "rho" : 0.5
       },
       "print_interval" :  100000,
       "h_penalty" : 32.,
       "g_penalties" : [200.],
       "g_targets" : [.1],
       "dbm_weight_decay" : [10],
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : !pkl: "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
                        "num_examples" : 100
                }
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

