!obj:pylearn2.scripts.train.Train {
    "dataset": &src !obj:galatea.s3c.s3c_dataset.S3C_Dataset {
        "raw" : !pkl: "${PYLEARN2_DATA_PATH}/stl10/stl10_32x32_whitened/unsupervised.pkl",
        "transformer" : !pkl: "/u/goodfeli/galatea/pddbm/config/stl/full/layer_1_C1.pkl"
    },
    "model": !obj:pylearn2.models.rbm.RBM {
               "nvis" : 8748,
               "nhid" : 400,
               "init_bias_hid" : 0.,
               "init_bias_vis" : -3.,
               "irange"  : .03,
               "base_lr" : .01,
               "monitor_reconstruction" : 1, 
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 100,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : *src,
                        "num_examples" : 100
                }
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

