#update of snapshot_003 for change to using self.h_coeff()
#I had been using the wrong energy function, this is an attempt to get things working with the right energy function in place
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: "/data/lisatmp/goodfeli/cifar10_preprocessed_train_2M.pkl",
    "model": !obj:galatea.s3c.s3c.S3C {
               "nvis" : 192,
               "nhid" : 300,
               "init_bias_hid" : -1.5,
               "irange"  : .5,
               "init_B"  : 3.,
               "min_B"   : 3.,
               "max_B"   : 3.,
               "init_alpha" : 1.,
               "min_alpha" : 1.,
               "max_alpha" : 1000.,
               "init_mu" : 1.,
               "N_schedule" : [1.,2.,4.,8.,16.,32.,64.,128.,256.,300.],
               "new_stat_coeff" : 1.0,
               "m_step"     : !obj:galatea.s3c.s3c.VHS_Solve_M_Step {
                        "new_coeff" : .01
               }
        },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 600,
               "batches_per_iter" : 5,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !pkl: "/data/lisatmp/goodfeli/cifar10_preprocessed_train_2M.pkl",
        },
    "save_path": "attempt_006.pkl"
}

