!obj:pylearn2.train.Train {
    dataset: &train !obj:galatea.esp.Im2Word {
        start: 0,
        stop: 90000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                     dim: 4000,
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     irange: .005
                 }
                ],
        # dropout_include_probs: [ .5, .5, 1 ],
        # dropout_input_include_prob: .8,
        # dropout_input_scale: 1.,
        nvis: 816,
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 1000,
        conjugate: 1,
        reset_alpha: 0,
        reset_conjugate: 0,
        updates_per_batch: 1,
        monitoring_dataset:
            {
                #'train' : *train,
                'train_subset' : !obj:galatea.esp.Im2Word {
                              start: 0,
                              stop:  1000
                          },
                'valid' : !obj:galatea.esp.Im2Word {
                              start: 90000,
                              stop:  100000
                          },
                #'test'  : !obj:pylearn2.datasets.mnist.MNIST {
                #              which_set: 'test',
                #              one_hot: 1,
                #          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts {
            costs: [
                !obj:galatea.esp.NegF1 {},
                !obj:pylearn2.costs.cost.MethodCost {
                    supervised: 1,
                    method: "cost_from_X"
                }
                ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_01_loss",
            prop_decrease: 0.,
            N: 100
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_f1',
             higher_is_better: 1,
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
