#initialize with random patches then learn only the weights
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
    "model": !obj:galatea.s3c.s3c.S3C {
               "nvis" : 108,
               "nhid" : 1600,
               "init_bias_hid" : -4.,
               "max_bias_hid" : -4.,
               "min_bias_hid" : -4.,
               "irange"  : .02,
               "constrain_W_norm" : 1,
               "init_B"  : 1.,
               "min_B"   : 1.,
               "max_B"   : 1.,
               "tied_B" :  1,
               "init_alpha" : 1.,
               "min_alpha" : 1.,
               "max_alpha" : 1.,
               "init_mu" : 0.,
               "random_patches_hack" : 1,
               "min_mu"  : 0.,
               "max_mu"  : 0.,
               #"recycle_q" : 1000,
               "print_interval" : 1,
               "monitor_functional" : 1,
               "monitor_params" : [ 'B', 'p', 'alpha', 'mu', 'W' ],
               #"monitor_stats" : [ 'mean_h', 'mean_hs', 'mean_sq_s', 'mean_sq_hs' ],
               "e_step" : !obj:galatea.s3c.s3c.Split_E_Step {
                        "h_new_coeff_schedule" : [ .1, .1, .1, .1, .1, .1, .1, .1, .2, .2, .2, .3, .3, .3, .4, .4, .4, .4, .4 ],
                        "s_new_coeff_schedule" : [  .7, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1 ],
                        "clip_reflections" : 1
                        #"monitor_em_functional" : 1
               },
               "new_stat_coeff" : 1.,
               #"learn_after" : 1000,
               "m_step"     : !obj:galatea.s3c.s3c.VHS_Grad_M_Step {
                        #"new_coeff" : .1
                        "learning_rate" : 1e-2,
                        "B_learning_rate_scale" : 0.01,
                        "W_learning_rate_scale" : 1.
               },
               "mu_eps" : 0.,
        },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 10,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !pkl: "${PYLEARN2_DATA_PATH}/stl10/stl10_patches/data.pkl",
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

