!obj:galatea.s3c.extract_features_rand_pool_python_loop.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "/RQexec/goodfell/B1.pkl",
        "save_path" :  "/RQexec/goodfell/B1_briaree_I.npy" ,
        "feature_type" : "exp_h",
        "dataset_family" : galatea.s3c.extract_features.cifar100,
        "restrict" : [ 40000,  45000 ],
        "which_set" : "train"
}