!obj:galatea.s3c.extract_features_rand_pool_python_loop.FeatureExtractor {
        "chunk_size" : 10000,
        "batch_size" : 1,
        "model_path" : "${GALATEA_PATH}/s3c/config/cifar100/B1.pkl",       
        "save_path" :  "${FEATURE_EXTRACTOR_YAML_PATH}.npy" , 
        "feature_type" : "exp_h", 
        "dataset_family" : galatea.s3c.extract_features.cifar100,
        "which_set" : "train"
}       
