!obj:galatea.s3c.extract_features.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "/RQexec/goodfell/C.pkl",
        "save_paths" : [ "/RQexec/goodfell/C_test_2_E.npy",
        "/RQexec/goodfell/C_test_3_E.npy",
        "/RQexec/goodfell/C_test_4_E.npy" ] ,
        "pooling_region_counts" : [ 2,3,4],
        "feature_type" : "exp_h",
        "dataset_family" : galatea.s3c.extract_features.cifar100,
        "restrict" : [ 4000,  5000 ],
        "which_set" : "test"
}