!obj:galatea.s3c.extract_features.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "/RQexec/goodfell/C.pkl",
        "save_paths" : [ "/RQexec/goodfell/C_test_2_B.npy",
        "/RQexec/goodfell/C_test_3_B.npy",
        "/RQexec/goodfell/C_test_4_B.npy" ] ,
        "pooling_region_counts" : [ 2,3,4],
        "feature_type" : "exp_h",
        "dataset_family" : galatea.s3c.extract_features.cifar100,
        "restrict" : [ 1000,  2000 ],
        "which_set" : "test"
}