!obj:galatea.s3c.extract_features_omp.FeatureExtractor {
    "chunk_size" : 10000,
    "batch_size" : 1,
    "save_paths" :  [ "/RQexec/goodfell/omp_3_800_train_0_25.npy"  ] ,
    "alpha" : 0.25,
    "num_bases" : 800,
    "pooling_region_counts" : [3],
    "dataset_family" : galatea.s3c.extract_features.cifar100,
    "which_set" : "train"
}
