#early attempt at using an E-step based on mean field in the original model
#like E2A2Q1 but with fewer hidden units
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: "${GOODFELI_TMP}/cifar10_preprocessed_train_2M.pkl",
    "model": !obj:galatea.s3c.s3c.S3C {
               "nvis" : 192,
               "nhid" : 300,
               "init_bias_hid" : -1.5,
               "irange"  : .02,
               "init_B"  : 3.,
               "min_B"   : 1e-8,
               "max_B"   : 1000,
               "tied_B" :  1,
               "init_alpha" : 1.,
               "min_alpha" : 1e-8,
               "max_alpha" : 1000.,
               "init_mu" : 0.,
               "min_mu"  : -1.,
               "max_mu"  : 1.,
               #"recycle_q" : 1000,
               "print_interval" : 1,
               "monitor_functional" : 1,
               "e_step" : !obj:galatea.s3c.s3c.VHS_E_Step {
                        "h_new_coeff_schedule" : [ .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7 ],
                        "s_new_coeff_schedule" : [ .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7, .7 ],
                        #"clip_reflections" : 1,
                        "monitor_em_functional" : 1
               },
               "new_stat_coeff" : 1.,
               #"learn_after" : 1000,
               "m_step"     : !obj:galatea.s3c.s3c.VHS_Solve_M_Step {
                        "new_coeff" : 1.
                        #"learning_rate" : 1e-3
               },
               "mu_eps" : 0.,
        },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 1000,
               "batches_per_iter" : 10,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !pkl: "${GOODFELI_TMP}/cifar10_preprocessed_train_2M.pkl",
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

