!obj:pylearn2.train.Train {
    dataset: &data !obj:pylearn2.datasets.binarizer.Binarizer { raw: !obj:pylearn2.datasets.mnist.MNIST {
        which_set: "train",
        one_hot: 1,
    }},
    model: !obj:galatea.dbm.inpaint.super_dbm.set_niter {
        super_dbm: !pkl: "${G}/dbm/inpaint/russ/pretrained.pkl", 
        niter: 11 # Russ's for loop does 10 iterations after the initial double weights pass,
                  # my algorithm counts the double weights pass as the first iteration
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
               learning_rate: 1e-3,
               init_momentum: .5,
               monitoring_batches: 10,
               monitoring_dataset : {
                  'raw_valid' : !obj:pylearn2.datasets.mnist.MNIST {
                        which_set: "train",
                        one_hot: 1,
                        start: 50000,
                        stop: 60000
               }},
               cost : !obj:pylearn2.costs.cost.SumOfCosts {
                costs: [ !obj:pylearn2.costs.dbm.VariationalPCD {
                        supervised: 1,
                        num_chains: 100,
                        num_gibbs_steps: 5,
                        toronto_neg: 1
                        },
                        !obj:galatea.dbm.inpaint.super_dbm.DBM_WeightDecay {
                          coeffs: [ .0001, .0001, .0001 ]
                        },
                        !obj:pylearn2.costs.dbm.TorontoSparsity {
                          supervised: 1,
                         targets: [ .2, .1, -1. ],
                         coeffs: [ .001, .001, 0. ],
                        }
                       ],
           },
           termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter { max_epochs: 300 },
           update_callbacks: [
                !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
                        decay_factor: 1.000015,
                        min_lr:       0.0001
                }
           ]
        },
    extensions: [
            !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
                final_momentum: .9,
                start: 5,
                saturate: 6
            },
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
}

