!obj:pylearn2.scripts.train.Train {
    save_path: "${EXPDIR}/pddbm_cifar100/${PYLEARN2_TRAIN_FILE_STEM}.pkl",
    dataset: !pkl: &src ${PYLEARN2_DATA_PATH}/cifar100/whitened/train.pkl,
    model: !obj:pylearn2.models.s3c.S3C {
               nvis : 3072,
               nhid : 169,
               local_rf_src: *src,
               local_rf_stride: [2,2],
               local_rf_shape: [8,8],
               init_bias_hid : -1.5,
               max_bias_hid : 1e6,
               min_bias_hid : -8.,
               irange  : .02,
               constrain_W_norm : 1,
               init_B  : 3.,
               min_B   : .1,
               max_B   : 1e6,
               tied_B :  0,
               init_alpha : 1.,
               min_alpha : .3,
               max_alpha : 1e6,
               init_mu : 0.,
               monitor_params : [ 'B', 'p', 'alpha', 'mu', 'W' ],
               m_step: !obj:pylearn2.models.s3c.Grad_M_Step {
                        learning_rate : .0005            
               },
               e_step: !obj:pylearn2.models.s3c.E_Step {
                monitor_kl : 1,
                clip_reflections : 1,
                rho : 0.5,
                s_new_coeff_schedule: [ .5, .5, .5, .5, .5, .5, 1.0 ],
                h_new_coeff_schedule: [ .5, .5, .5, .5, .5, 1.0, 1.0]
               }
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 100,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : *src,
                        "num_examples" : 100
                }
        },
    "save_freq": 1
}

