!obj:galatea.s3c.extract_features.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "${GALATEA_PATH}/s3c/config/stl/P.pkl",         "pooling_region_counts": [3],
        "save_paths" : [ "${FEATURE_EXTRACTOR_YAML_PATH}.npy" ], 
        "feature_type" : "exp_h", 
        "dataset_family" : galatea.s3c.extract_features.stl10,
        "which_set" : "train"
}       
