!obj:pylearn2.scripts.train.Train {
    dataset: &dataset !pkl: "${CIFAR10_PATCHES_6x6}",
    model: !obj:pylearn2.models.rbm.GaussianBinaryRBM {
        "nvis" : 108,
        "nhid" : 400,
        "irange" : 0.05,
        "energy_function_class" : !obj:pylearn2.energy_functions.rbm_energy.grbm_type_1 {},
        "learn_sigma" : True,
        "init_sigma" : .4,
        "init_bias_hid" : -2.,
        "mean_vis" : False,
        "sigma_lr_scale" : 1e-3

    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batches_per_iter: 10,
        line_search_mode: 'exhaustive',
        hacky_conjugacy: 1,
        reset_conjugate: 0,
        reset_alpha: 0,
        updates_per_batch: 3,
        batch_size: 1000,
        monitoring_batches : 1,
        monitoring_dataset : *dataset,
        cost : !obj:pylearn2.costs.ebm_estimation.SM {
        },
    },
    #Finally, request that the model be saved after each epoch
    "save_freq" : 1
}


