!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.cifar10.CIFAR10 {
        axes: ['c', 0, 1, 'b'],
        which_set: 'train',
        gcn: 55.,
        one_hot: 1,
        start: 0,
        stop: 40000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h0',
                     pad: 7,
                     detector_channels: 720,
                     channel_pool_size: 6,
                     kernel_shape: [2, 2],
                     pool_shape: [3, 3],
                     pool_stride: [7, 7],
                     irange: 0.328132,
                     max_kernel_norm: 2.110937,
                 },
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h1',
                     pad: 4,
                     detector_channels: 448,
                     channel_pool_size: 2,
                     kernel_shape: [1, 1],
                     pool_shape: [6, 6],
                     pool_stride: [8, 8],
                     irange: 0.828127,
                     max_kernel_norm: 9.226562,
                 },
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h2',
                     pad: 10,
                     detector_channels: 16,
                     channel_pool_size: 8,
                     kernel_shape: [3, 3],
                     pool_shape: [10, 10],
                     pool_stride: [3, 3],
                     irange: 0.265632,
                     max_kernel_norm: 9.226562,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 4.585938,
                     layer_name: 'y',
                     n_classes: 10,
                     irange: 0.421881
                 }
                ],
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [32, 32],
            axes: ['c', 0, 1, 'b'],
            num_channels: 3
        },
        dropout_include_probs: [ 0.852187, 0.423438, 0.270313, 1 ],
        dropout_scales: [ 67.515625, 30.390625, 18.015625, 1. ],
        dropout_input_include_prob: 0.607187,
        dropout_input_scale: 89.171875,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 128,
        learning_rate: 4.843750,
        init_momentum: 0.448594,
        monitoring_dataset:
            {
                'valid' : !obj:pylearn2.datasets.cifar10.CIFAR10 {
                              which_set: 'train',
                              axes: ['c', 0, 1, 'b'],
                              gcn: 55.,
                              one_hot: 1,
                              start: 40000,
                              stop:  50000
                          },
            },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.051562,
            min_lr: .000001
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 71,
            final_momentum: 0.077344
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
