!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.cifar10.CIFAR10 {
        axes: ['c', 0, 1, 'b'],
        which_set: 'train',
        gcn: 55.,
        one_hot: 1,
        start: 0,
        stop: 40000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h0',
                     pad: 2,
                     detector_channels: 416,
                     channel_pool_size: 8,
                     kernel_shape: [8, 8],
                     fix_kernel_shape: 1,
                     pool_shape: [3, 3],
                     fix_pool_shape: 1,
                     pool_stride: [10, 10],
                     irange: 0.025483,
                     max_kernel_norm: 4.740625,
                 },
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h1',
                     pad: 9,
                     detector_channels: 688,
                     channel_pool_size: 8,
                     kernel_shape: [8, 8],
                     fix_kernel_shape: 1,
                     pool_shape: [1, 1],
                     fix_pool_shape: 1,
                     pool_stride: [10, 10],
                     irange: 0.010746,
                     max_kernel_norm: 5.359375,
                 },
                 !obj:galatea.mlp.ConvLinearC01B {
                     layer_name: 'h2',
                     pad: 2,
                     detector_channels: 368,
                     channel_pool_size: 2,
                     kernel_shape: [3, 3],
                     fix_kernel_shape: 1,
                     pool_shape: [7, 7],
                     fix_pool_shape: 1,
                     pool_stride: [2, 2],
                     irange: 0.805842,
                     max_kernel_norm: 5.359375,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1.646875,
                     layer_name: 'y',
                     n_classes: 10,
                     irange: 0.009306
                 }
                ],
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [32, 32],
            axes: ['c', 0, 1, 'b'],
            num_channels: 3
        },
        dropout_include_probs: [ 0.591875, 0.775625, 0.040625, 1 ],
        dropout_scales: [ 35.031250, 96.906250, 22.656250, 1. ],
        dropout_input_include_prob: 0.040625,
        dropout_input_scale: 84.531250,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 128,
        learning_rate: 0.000205,
        init_momentum: 0.525937,
        monitoring_dataset:
            {
                'valid' : !obj:pylearn2.datasets.cifar10.CIFAR10 {
                              which_set: 'train',
                              axes: ['c', 0, 1, 'b'],
                              gcn: 55.,
                              one_hot: 1,
                              start: 40000,
                              stop:  50000
                          },
            },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.002077,
            min_lr: .000001
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 454,
            final_momentum: 0.897188
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
