!obj:framework.scripts.train.Train {
    "dataset": !pkl: "/u/goodfeli/ift6266h11/recons_srbm/cifar10_preprocessed_train.pkl",
    "model": !obj:framework.models.local_noise_ebm.LocalNoiseRBM {
                "nvis" : 192,
                "nhid" : 400,
                "init_bias_hid" : -1.0,
                "irange"  : .05,
                "init_noise_var"    : .15,
                "min_misclass"  : .05,
                "max_misclass"  : .1,
                "noise_var_scale_up" : 1.001,
                "noise_var_scale_down" : .999,
                "max_noise_var"       : 1.,
                "time_constant"  : .1,
                "learning_rate" : .0002,
                "different_examples" : 1,
                "energy_function" : "gaussian-binary rbm",
                "init_vis_prec" : 25.0,
                "learn_vis_prec" : 0
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 5,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 10,
               "monitoring_dataset" : !pkl: "/u/goodfeli/ift6266h11/recons_srbm/cifar10_preprocessed_test.pkl"
    },
    "save_path": "rbm.pkl"
}

