!obj:framework.scripts.train.Train {
    "dataset": !pkl: "mnist_preprocessed_train.pkl",
    "model": !obj:framework.models.local_noise_rbm.LocalNoiseRBM {
                "nvis" : 784,
                "nhid" : 400,
                "init_bias_hid" : 0.0,
                "irange"  : .05,
                "init_beta"    : .001,
                "min_misclass"  : .05,
                "max_misclass"  : .1,
                "beta_scale_up" : 1.001,
                "beta_scale_down" : .999,
                "max_beta"       : 1.,
                "time_constant"  : .1,
                "learning_rate" : .002
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 5,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 10,
               "monitoring_dataset" : !pkl: "mnist_preprocessed_train.pkl"
        },
    "save_path": "rbm_mnist.pkl"
}

