!obj:framework.scripts.train.Train {
    "dataset": !obj:framework.datasets.cos_dataset.CosDataset {},
    "model": !obj:framework.models.local_noise_ebm.LocalNoiseEBM {
                "nvis" : 2,
                "nhid" : 400,
                "init_bias_hid" : 0.0,
                "irange"  : 2.5,
                "init_noise_var"    : 2.0,
                "min_misclass"  : .05,
                "max_misclass"  : .5,
                "noise_var_scale_up" : 1.001,
                "noise_var_scale_down" : .999,
                "max_noise_var"       : 2.,
                "time_constant"  : .1,
                "learning_rate" : .0002,
                "different_examples" : 1.,
                "init_vis_prec" : 1.,
                "learn_vis_prec" : 1.,
                "vis_prec_lr_scale" : .001,
                "energy_function" : "mse autoencoder",
                "init_delta" : -0.5
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 5,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 10,
               "monitoring_dataset" : !obj:framework.datasets.cos_dataset.CosDataset {},

        },
    "save_path": "autoencoder_cos.pkl"
}

