!obj:framework.scripts.train.Train {
    "dataset": !pkl: "mnist_preprocessed_train.pkl",
    "model": !obj:framework.models.local_noise_rbm.LocalNoiseRBM {
                "nvis" : 784,
                "nhid" : 400,
                "init_bias_hid" : 0.0,
                "irange"  : .05,
                "init_noise_var"    : 1.0,
                "min_misclass"  : .05,
                "max_misclass"  : .1,
                "noise_var_scale_up" : 1.001,
                "noise_var_scale_down" : .999,
                "max_noise_var"       : 10.,
                "time_constant"  : .1,
                "learning_rate" : .002,
                "different_examples" : 1,
                "init_vis_prec" : 1.,
                "learn_vis_prec" : 0
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 5,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 10,
               "monitoring_dataset" : !pkl: "mnist_preprocessed_train.pkl"
        },
    "save_path": "rbm_mnist_diff.pkl"
}

