!obj:galatea.s3c.extract_features.FeatureExtractor {
    "batch_size" : 1,
    "model_path" : "/data/lisatmp2/goodfeli/s3c_cifar100_patches/C3.pkl",
    "save_paths" : [ "/data/lisatmp2/goodfeli/C3_lab_3_mean.npy" ] ,
    "pooling_region_counts" : [ 3 ],
    "feature_type" : "exp_h",
    "dataset_family" : galatea.s3c.extract_features.cifar100,
    "chunk_size" : 10000,
    "which_set" : "train",
    "pool_mode" : "mean"
}

