#like L1 but more damped
#L1 instruments showed that even first step of damped mean field was causing trouble
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: "${GOODFELI_TMP}/cifar10_preprocessed_train_2M.pkl",
    "model": !obj:galatea.s3c.s3c.S3C {
               "nvis" : 192,
               "nhid" : 4000,
               "init_bias_hid" : -3.,
               "max_bias_hid" : -3.,
               "irange"  : .02,
               "constrain_W_norm" : 1.,
               "init_B"  : 3.,
               "min_B"   : 1e-8,
               "max_B"   : 1e6,
               "tied_B" :  1,
               "init_alpha" : 1.,
               "min_alpha" : 1e-8,
               "max_alpha" : 1000.,
               "init_mu" : 0.,
               #"min_mu"  : -1.,
               #"max_mu"  : 1.,
               #"recycle_q" : 1000,
               "print_interval" : 1,
               "monitor_functional" : 1,
               "monitor_norms" : 1,
               "monitor_params" : [ 'W', 'B', 'alpha', 'mu', 'p' ],
               "monitor_stats" : [ 'mean_h', 'mean_hs', 'mean_sq_s', 'mean_sq_hs' ],
               "e_step" : !obj:galatea.s3c.s3c.VHS_E_Step {
                        "h_new_coeff_schedule" : [ .1, .1, .1, .1, .1, .1, .1, .1, .7, .7, .7, .7, .7, .7, .7 ],
                        "s_new_coeff_schedule" : [ .05, .05, .05, .05, .05, .05, .05, .05, .1, .1, .1, .1, .1, .1, .1 ],
                        "clip_reflections" : 1,
                        "monitor_em_functional" : 1
               },
               "new_stat_coeff" : 1.,
               #"learn_after" : 1000,
               "m_step"     : !obj:galatea.s3c.s3c.VHS_Solve_M_Step {
                        "new_coeff" : .1
                        #"learning_rate" : 1e-3
               },
               "mu_eps" : 0.,
        },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 1000,
               "batches_per_iter" : 10,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !pkl: "${GOODFELI_TMP}/cifar10_preprocessed_train_2M.pkl",
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

