
!obj:framework.scripts.train.Train {
    "dataset": !pkl: &data "/data/lisatmp/goodfeli/cifar10_preprocessed_train.pkl",
    "model": !obj:recons_srbm.br_recons_srbm.BR_ReconsSRBM {
                "nvis" : 192,
                "nhid" : 400,
                "init_bias_hid" : -2.072342,
                "irange"  : 0.014345,
                "init_beta"    : 2.795510,
                "learn_beta" : 1,
                "beta_lr_scale" : 0.003789,
                "mean_field_iters" : 10,
                "damping_factor" : 0.406090,
                "no_damp_iters" : 1,
                "gibbs_iters" : 1,
                "persistent_chains" : 1,
                "enc_weight_decay" : 0.000099,
                "learning_rate" : 0.000430,
                "fold_biases" : 0.000000,
                "use_cd" : 0.000000
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 3,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 10,
               "monitoring_dataset" : *data
    },
    "save_path": "/data/lisatmp/goodfeli/expdir/recons_srbm_2/models/model_6.pkl"
}
