!obj:framework.scripts.train.Train {
    "dataset": !pkl: "cifar10_preprocessed_train.pkl",
    "model": !obj:recons_srbm.br_recons_srbm.BR_ReconsSRBM {
                "nvis" : 192,
                "nhid" : 400,
                "init_bias_hid" : 0.0,
                "irange"  : 0.05,
                "beta"    : 3.0,
                "mean_field_iters" : 1,
                "damping_factor" : 0.5,
                "gibbs_iters" : 1,
                "persistent_chains" : 5,
                "enc_weight_decay" : .003,
                "learning_rate" : .000000002,
                "fold_biases" : 1.
        },
    "algorithm": !obj:framework.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 5,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 100,
               "monitoring_dataset" : !pkl: "/u/goodfeli/ift6266h11/recons_srbm/cifar10_preprocessed_train.pkl"
    },
    "save_path": "rbm.pkl"
}

