!obj:framework.scripts.train.Train {
    "dataset": !pkl: "/u/goodfeli/ift6266h11/recons_srbm/cifar10_preprocessed_train.pkl",
    "model": !obj:framework.autoencoder.DenoisingAutoencoder {
                "nvis" : 192,
                "nhid" : 20,
                "act_enc" : null,
                "act_dec" : null,
                "irange"  : 0.00001,
                "tied_weights" : true,
                "corruptor": !obj:framework.corruption.GaussianCorruptor {
                               "corruption_level" : 0.15
                        }
        },
    "algorithm": !obj:framework.training_algorithms.demo.Demo {
                "base_lr"  :  1e-5
    },
}

