!obj:pylearn2.scripts.train.Train {
    "dataset": &src !obj:galatea.s3c.s3c_dataset.S3C_Dataset {
        "raw" : !pkl: "${CIFAR100_PATCHES_6x6}",
        "transformer" : !pkl: "/data/lisatmp2/goodfeli/s3c_cifar100_patches/C3.pkl"
    },
    "model": !obj:pylearn2.models.rbm.RBM {
               "nvis" : 1600,
               "nhid" : 3200,
               "init_bias_hid" : -1.,
               "irange"  : .05,
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 1000,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : *src,
                        "num_examples" : 100
                }
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl"
}

