!obj:pylearn2.train.Train {
    dataset: &data !obj:galatea.datasets.zca_dataset.ZCA_Dataset {
        preprocessed_dataset: !pkl: "${PYLEARN2_GCN_WHITENED}/train.pkl",
        preprocessor: !pkl: "${PYLEARN2_GCN_WHITENED}/preprocessor.pkl"
    },
    model: !obj:galatea.dbm.inpaint.super_dbm.SuperDBM {
              inference_procedure: !obj:galatea.dbm.inpaint.super_dbm.BiasInit {},
              batch_size : 100,
              niter: 6,
              visible_layer: !obj:galatea.dbm.inpaint.super_dbm.GaussianConvolutionalVisLayer {
              # Naturally centered already
                rows: 32,
                cols: 32,
                channels: 3,
                init_beta: 3.7,
                init_mu: 0.
              },
              hidden_layers: [
                                !obj:galatea.dbm.inpaint.super_dbm.ConvMaxPool {
                                        center: 1,
                                        scale_by_sharing: 0,
                                        border_mode : 'full',
                                        output_channels: 64,
                                        kernel_rows: 8,
                                        kernel_cols: 8,
                                        pool_rows: 3,
                                        pool_cols: 3,
                                        irange: 0.00,
                                        layer_name: 'h0_conv',
                                        init_bias: -5.
                               },
                                !obj:galatea.dbm.inpaint.super_dbm.ConvMaxPool {
                                        center: 1,
                                        scale_by_sharing: 0,
                                        border_mode : 'full',
                                        output_channels: 64,
                                        kernel_rows: 4,
                                        kernel_cols: 4,
                                        pool_rows: 2,
                                        pool_cols: 2,
                                        irange: .00,
                                        layer_name: 'h1_conv',
                                        init_bias: -4.
                               },
                !obj:galatea.dbm.inpaint.super_dbm.DenseMaxPool {
                        center: 1,
                        pool_size : 1,
                        detector_layer_dim: 400,
                        irange: 0.,
                        init_bias: 0.,
                        layer_name: 'h2_dense'
                },
              !obj:galatea.dbm.inpaint.super_dbm.Softmax {
                        center: 1,
                        layer_name: "c",
                        irange: 0.,
                        n_classes: 10
              }
              ]
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
               learning_rate: 1e-3,
               batches_per_iter : 100,
               monitoring_batches : 10,
               monitoring_dataset : *data,
               cost : !obj:pylearn2.costs.cost.SumOfCosts {
                costs: [
                        !obj:pylearn2.costs.dbm.VariationalPCD {
                                supervised: 1,
                                num_gibbs_steps: 5,
                                num_chains: 100
                        }
                       ]
               },
        },
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
}

