!obj:pylearn2.train.Train {
    dataset: &data !obj:galatea.datasets.zca_dataset.ZCA_Dataset {
        preprocessed_dataset: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/train.pkl",
        preprocessor: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/preprocessor.pkl",
        axes: ['b', 'c', 0, 1]
    },
    model: !obj:galatea.dbm.inpaint.super_dbm.SuperDBM {
              batch_size : 128,
              niter: 6, 
              visible_layer: !obj:galatea.dbm.inpaint.super_dbm.GaussianConvolutionalVisLayer {
                rows: 32,
                cols: 32,
                channels: 3,
                init_beta: 3.7,
                init_mu: 0.,
                axes: ['b', 'c', 0, 1]
              },
              hidden_layers: [
                    !obj:galatea.dbm.inpaint.super_dbm.ConvMaxPool {
                            border_mode : 'full',
                            output_channels: 32,
                            kernel_rows: 9,
                            kernel_cols: 9,
                            pool_rows: 2,
                            pool_cols: 2,
                            irange: 0.05,
                            layer_name: 'h0_conv',
                            init_bias: -5.
                   },
                   !obj:galatea.dbm.inpaint.super_dbm.ConvMaxPool {
                            border_mode : 'full',
                            output_channels: 64,
                            kernel_rows: 5,
                            kernel_cols: 5,
                            pool_rows: 3,
                            pool_cols: 3,
                            irange: 0.3,
                            layer_name: 'h1_conv',
                            init_bias: -4.5
                   },
                    !obj:galatea.dbm.inpaint.super_dbm.ConvMaxPool {
                            border_mode : 'full',
                            output_channels: 64,
                            kernel_rows: 3,
                            kernel_cols: 3,
                            pool_rows: 2,
                            pool_cols: 2,
                            irange: 0.3,
                            layer_name: 'h2_conv',
                            init_bias: -4.
                    },
                   !obj:galatea.dbm.inpaint.super_dbm.Softmax {
                            max_col_norm: 4.,
                            sparse_init: 0,
                            layer_name: 'c',
                            n_classes: 10
                   }
                    ]
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        monitoring_dataset : {
            'valid' :  !obj:galatea.datasets.zca_dataset.ZCA_Dataset {
                    preprocessed_dataset: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/train.pkl",
                    preprocessor: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/preprocessor.pkl",
                    start: 40000,
                    stop: 50000,
                    axes: ['b', 'c', 0, 1]
                },
            }, 
        learning_rate: 15.146493,
        init_momentum: .5,
        cost: &cost !obj:pylearn2.costs.cost.SumOfCosts {
            costs: [
                !obj:galatea.dbm.inpaint.super_inpaint.SuperInpaint {          
                    both_directions: 0,
                    noise: 0,
                    supervised: 1,
                    mask_gen: !obj:galatea.dbm.inpaint.super_inpaint.MaskGen {
                        drop_prob: 0.5,
                        balance: 0,
                        sync_channels: 0
                   }
                }
            ]
        },
       termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased
       {
                channel_name: "valid_err",
                N: 100,
                prop_decrease: 0.
       },
    },
    extensions: [
                !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
                        channel_name: "valid_err",
                        save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
                },
                !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
                    start: 1,
                    saturate: 2,
                    final_momentum: 0.732716
                },
                !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
                    start: 1,
                    saturate: 868,
                    decay_factor: 0.020379
                }
        ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
} 
