# Linear regression gets about 65% valid acc on N3_interm features but
# cifar10_sup_A7 can't seem to get above 10%.
# Is this an effect of trying to train the model jointly?
# Here I train just the last layer, on frozen output from N3_interm
!obj:pylearn2.scripts.train.Train {
    dataset:  !obj:galatea.datasets.hack_dataset.HackDataset {
        labels_from: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/train.pkl",
        X: !pkl: "/u/goodfeli/galatea/dbm/inpaint/expdir/cifar10_N3_interm_2_features.pkl",
        start: 0,
        stop: 40000
    },
    model: !obj:galatea.dbm.inpaint.super_dbm.LayerAsClassifier {
        nvis: 3200,
        layer: !obj:galatea.dbm.inpaint.super_dbm.Softmax {
                        irange: 0.05,
                        n_classes: 10,
                        layer_name: 'class_layer',
      }
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
               learning_rate: 1e-1,
               init_momentum: .5,
               batch_size: 25,
               set_batch_size: 1,
               monitoring_dataset :   !obj:galatea.datasets.hack_dataset.HackDataset {
        labels_from: !pkl: "/data/lisa/data/cifar10/pylearn2_gcn_whitened/train.pkl",
        X: !pkl: "/u/goodfeli/galatea/dbm/inpaint/expdir/cifar10_N3_interm_2_features.pkl",
        start: 40000,
        stop: 50000
    },
               cost : !obj:galatea.dbm.inpaint.super_dbm.SuperDBM_ConditionalNLL {
               },
        },
    callbacks: [ !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
                        start: 0,
                        saturate: 10,
                        final_momentum: .9
                  }
                ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
}

