
!obj:pylearn2.train.Train {
    dataset:  &train !obj:pylearn2.datasets.mnist.MNIST {
        which_set: "train",
        #binarize: 1,
        one_hot: 1,
    },
        model: !obj:galatea.dbm.inpaint.super_dbm.MLP_Wrapper {
                        decapitate: 1,
                        super_dbm: !obj:galatea.dbm.inpaint.super_dbm.set_niter {
                                super_dbm: !pkl: "expdir/mnist_sup_inpaint_X3E_retrain.pkl",
                                niter: 6
                        },
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
               line_search_mode: 'exhaustive',
               batch_size: 100,
               set_batch_size: 1,
               updates_per_batch: 3,
               reset_alpha: 0,
               conjugate: 1,
               reset_conjugate: 0,
               monitoring_dataset: {
                                'train' : *train,
                                'test' : !obj:pylearn2.datasets.mnist.MNIST {
                                        which_set: "test",
                                        #binarize: 1,
                                        one_hot: 1,
                                        }
               },
               cost : !obj:galatea.dbm.inpaint.super_dbm.SuperDBM_ConditionalNLL {
               },
               termination_criterion: !obj:pylearn2.termination_criteria.ChannelTarget
               {
                        channel_name: "train_objective",
                        target: 6.01598742378e-07
               }
        },
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq : 1
}
