!obj:galatea.s3c.extract_features_rand_pool_python_loop.FeatureExtractor {
        "chunk_size" : 10000,
        "batch_size" : 1,
        "model_path" : "/RQexec/goodfell/G1r.pkl",       
        "save_path" :  "/RQexec/goodfell/${FEATURE_EXTRACTOR_YAML_NAME}.npy" , 
        "feature_type" : "exp_h", 
        "dataset_family" : galatea.s3c.extract_features.cifar10,
        "which_set" : "train"
}       
