!obj:galatea.s3c.extract_features.FeatureExtractor {
        "batch_size" : 1,
        "model_path" : "${GALATEA_PATH}/s3c/config/6x6/G.pkl",         "pooling_region_counts": [2,3],
        "save_paths" : [ "${FEATURE_EXTRACTOR_YAML_PATH}_2.npy",  "${FEATURE_EXTRACTOR_YAML_PATH}_3.npy" ], 
        "feature_type" : "exp_h", 
        "dataset_name" : "cifar10",
        "restrict" : [45000,50000],
        "which_set" : "train"
}       
