#like D4 but added penalty on h
!obj:pylearn2.scripts.train.Train {
    "dataset": !pkl: &src "${CIFAR100_PATCHES_8x8}",
    "model": !obj:galatea.pddbm.pddbm.PDDBM {
        "freeze_s3c_params" : 1,
        "h_bias_src" : "s3c",
        "learning_rate" : .005,
        "dbm": !obj:pylearn2.models.dbm.DBM {
                "negative_chains" : 100,
                "monitor_params" : 1,
                "rbms" : [ !obj:pylearn2.models.rbm.RBM {
                        "nvis" : 400,
                        "nhid" : 1200,
                        "init_bias_hid" : -1,
                        "irange" : .05,
                        #"random_patches_src" : !obj:galatea.s3c.s3c_dataset.S3C_Dataset {
                        #"raw" : *src,
                        #"transformer" : !pkl: &s3c "/u/goodfeli/galatea/pddbm/config/stl/full/layer_1_C1.pkl",
                        #"cpu_only" : 1
                        #},
                        "monitor_reconstruction" : 1
                }]
        },
        "s3c":  !pkl: &s3c "/u/goodfeli/galatea/pddbm/config/cifar100/8x8/layer_1_A.pkl",
       "inference_procedure" : !obj:galatea.pddbm.pddbm.InferenceProcedure {
                "schedule" : [ ['s',1.],   ['h',1.],   ['g',0],   ['h', 0.4], ['s',0.4],
                             ['h',0.4], ['g',0],   ['h',0.4], ['s',0.4],  ['h',0.4],
                             ['g',0],   ['h',0.4], ['s',0.4], ['h', 0.4], ['g',0],
                             ['h',0.4], ['g',0],   ['h',0.4], ['s', 0.4], ['h',0.4] ],
                "monitor_kl" : 0,
                "clip_reflections" : 1,
                "rho" : 0.5
       },
       "print_interval" :  100000,
       #"h_penalty" : 32.,
       #"g_penalties" : [200.],
       #"g_targets" : [.1],
       #"dbm_weight_decay" : [10],
    },
    "algorithm": !obj:pylearn2.training_algorithms.default.DefaultTrainingAlgorithm {
               "batch_size" : 100,
               "batches_per_iter" : 500,
               "monitoring_batches" : 1,
               "monitoring_dataset" : !obj:pylearn2.datasets.dense_design_matrix.from_dataset {
                        "dataset" : *src,
                        "num_examples" : 100
                }
        },
    "save_path": "${PYLEARN2_TRAIN_FILE_NAME}.pkl",
    "save_freq": 1
}

